### PR TITLE
IItemEmc fixes

### LINKED ISSUE #1632: IItemEmc assumptions
IItemEmc assumes klein star in many cases

### PR DESCRIPTION
**Pull request by Mordenkainen**
Fixes for various issues where PE made some assumptions when dealing with IItemEmcs and such.

There may be other locations I haven't found yet.

fixes #1632

### CODE REVIEW

File: src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotInput.java [hunk 1]
```diff
@@ -51,7 +52,9 @@ public void putStack(@Nonnull ItemStack stack)
 			}
 		}
 
-		inv.handleKnowledge(stack.copy());
+		if (EMCHelper.doesItemHaveEmc(stack)) {
+			inv.handleKnowledge(stack.copy());
```
Comment (williewillus) [inline src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotInput.java]: what's the if needed for, doesn't the isItemValid change guarantee anything coming in to putStack have a emc value?

File: src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java [hunk 2]
```diff
@@ -53,7 +54,9 @@ public void putStack(@Nonnull ItemStack stack)
 			}
 		}
 		
-		inv.handleKnowledge(stack.copy());
+		if (EMCHelper.doesItemHaveEmc(stack)) {
+			inv.handleKnowledge(stack.copy());
+		}
```
Comment (williewillus) [inline src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java]: same here

File: src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotInput.java (hunk 1 above)
Comment (Mordenkainen) [reply src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotInput.java]: actually no.... It is an assumption that because something is an IItemEmc that it also has an EMC value, but it doesn't have to. For example, my EMC storage cells are IItemEmc's, but have no EMC value of their own.

File: src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java (hunk 2 above)
Comment (Mordenkainen) [reply src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java]: same here
